### ISSUE TITLE
problem about hdr psnr in paper

### ISSUE THREAD

**Issue by flyyyy** [pratulsrinivasan/lighthouse#2]
I saw you use psnr to compare with other methods in paper, however, in psnr, we need to define a pixel max-value.In ldr, we usually set it to 255 or 1(after normalization). 
In hdr, we store value in float, which max-value did you use?
Thx very much.

**Comment by pratulsrinivasan** [comment]
Hi! We used LDR environment maps (by tone-mapping and clipping) for the quantitative comparisons, since the InteriorNet dataset does not have ground-truth HDR environment maps. The maximum value was 1 for these experiments.
